### PR TITLE
Add .gitignore

### PR DESCRIPTION
**Pull request by qiangyt**

### CODE REVIEW

**Comment by ethancommitpush** [comment]
@qiangyt 
As I see these lines below on the top of the .gitignore are not as common as other lines: 
```text
HELP.md
!.mvn/wrapper/maven-wrapper.jar
!**/src/main/**/target/
!**/src/test/**/target/
```
Would you please remove these lines? Thanks.
By the way, I will release version 1.1.3 with the bugfix you submitted to Maven repository after merging this pull request.

**Comment by qiangyt** [comment]
> @qiangyt
> As I see these lines below on the top of the .gitignore are not as common as other lines:
> 
> ```
> HELP.md
> !.mvn/wrapper/maven-wrapper.jar
> !**/src/main/**/target/
> !**/src/test/**/target/
> ```
> 
> Would you please remove these lines? Thanks.
> By the way, I will release version 1.1.3 with the bugfix you submitted to Maven repository after merging this pull request.

It is generated by spring initializer (https://start.spring.io/).
The purpose is to avoid accidentally ignoring some code like src/main/java/example/target/Test.java.

Actually, I just trust what's generated by spring initializer before and didn't realize the reason behind it. Now I verified the behavior of `!**/src/main/**/target/` and I agree it.

**Comment by ethancommitpush** [comment]
@qiangyt
Yep, I also agree with that part you mentioned, thanks for your kind reminder :)
One more thing, about the ```HELP.md```, this is for ignoring the file generated by Spring initializer, 
and since that file is only about to inform developers where the reference documentation are, 
I would need your help to remove just that one line.
Cheers.

**Comment by qiangyt** [comment]
> @qiangyt
> Yep, I also agree with that part you mentioned, thanks for your kind reminder :)
> One more thing, about the `HELP.md`, this is for ignoring the file generated by Spring initializer,
> and since that file is only about to inform developers where the reference documentation are,
> I would need your help to remove just that one line.
> Cheers.

Got it. I updated it.

**Pull request merged**
