### PR TITLE
Customizable encoder/decoder/client/errorDecoder etc.

### PR DESCRIPTION
**Pull request by qiangyt**
1) Move feign client builder method from registrar to separated factory bean
2) Customization style:
    - default properties are in FeignClientsProperties
    - FeignClient annotation could overrides default properties, if specified
    - for each customizable component, customization is done via a pair of class/bean name which is exclusive.
3) add unit test cases.

### CODE REVIEW

**Comment by qiangyt** [comment]
@ethancommitpush , could you help to review it?

**Comment by ethancommitpush** [comment]
@qiangyt, sure, I was thinking about to finish the review later today, I will keep you posted on this.

**Comment by qiangyt** [comment]
> @qiangyt, sure, I was thinking about to finish the review later today, I will keep you posted on this.

I'm working on a demo project (https://github.com/engineer-365/fleashop-server), its target is k8s native and no springcloud, so springcloud feign starter is not good for it and so the idea is awesome for my case!

**Comment by qiangyt** [comment]
Another thought about this PR is hwo to simplify how to do customization. In this PR, there're 2 kinds:
1) specify a class then will instantiate it, e.g. FeignClient.decoder
2) specify a bean, e.g. FeignClient.decoderBean

How about retire approach #1? #1 in this PR for backward-compatibility, and I think it's rarely useful - in most of cases, the customized code depends on other beans or properties, but it is difficult for  instance created by #1 to talk with Spring to have dependence injects. For example, for my customized jackson decoder, why I need to customize it is I'd like to use specific jackson ObjectMapper which may be another bean managed by spring.

The PR could be quite simplified if approach #1 is removed.

**Comment by qiangyt** [comment]
In addition, how about splits into 3 separated sub-projects, as:
1. core - most of current code will go into this sub-project.
2. dependencies - pure pom, includes openfeign, jackson (optional), and so on. #1 depends on #2.
3. starter - pure pom too, includes #1 and #2.
Then user could uses #3 only for most cases, the benefit is that users no need to explicitly include dependences which is covered by #2, what they need to do is to decare a single dependence (#3) only.

I could submit another PR for this.

**Comment by ethancommitpush** [comment]
@qiangyt I just finished reviewing your commit.
The feature you introduced is quite nice, 
here are my opinions about some issues: 
1. ```FeignLoggerKind``` owns a static method to be called to create loggers, we should better to make enum for storing values only, and move the logger creation method to ```FeignClientsFactory```; and the naming is not quite strightforward, should be rename to FeignLoggerType. 
2. ```FeignClientsProperties``` was exposed to be configurable in properties file via ```@EnableConfigurationProperties``` and ```@ConfigurationProperties``` annotation:  
As I see we should expose only logLevel and loggerType to be configurable in the properties file, other attributes should only be accessed via getter method for creating default encoder/decoder/errorDecoder/client beans in ```FeignClientsAutoConfiguration```. 
As now users would face the application failed to start problem just because they add one line to the properties file like this, and eventually break the decoder-docderBean exclusive rule: 
    ```yaml
    feign.default-decoder-bean: myDecoder
    ``` 
    And this is somehow related to what you mentioned on the [comment-761522346](https://github.com/ethancommitpush/spring-boot-starter-openfeign/pull/3#issuecomment-761522346): 
    > 1&#46; specify a class then will instantiate it, e.g. FeignClient.decoder
    >
    > The PR could be quite simplified if approach # 1 is removed.

    I suggest to expose setter method for only logLevel and loggerType, and remove attributes similar to defaultDecoderBean: 
    ```java
    @ConfigurationProperties("feign")
    public class FeignClientsProperties {
        private Logger.Level logLevel = Logger.Level.BASIC;
        private FeignLoggerType loggerType = FeignLoggerType.SYSTEM_ERR;
        private Class<? extends Decoder> defaultDecoderClass = JacksonDecoder.class;
        private Class<? extends Encoder> defaultEncoderClass = JacksonEncoder.class;
        private Class<? extends ErrorDecoder> defaultErrorDecoderClass = CustomErrorDecoder.class;
        private Class<? extends Client> defaultClientClass = ApacheHttpClient.class;
    
        public Logger.Level getLogLevel() {
            return logLevel;
        }
        public void setLogLevel(Logger.Level logLevel) {
            this.logLevel = logLevel;
        }
        public FeignLoggerType getLoggerType() {
            return loggerType;
        }
        public void setLoggerType(FeignLoggerType loggerType) {
            this.loggerType = loggerType;
        }
        public Class<? extends Decoder> getDefaultDecoderClass() {
            return defaultDecoderClass;
        }
        public Class<? extends Encoder> getDefaultEncoderClass() {
            return defaultEncoderClass;
        }
        public Class<? extends ErrorDecoder> getDefaultErrorDecoderClass() {
            return defaultErrorDecoderClass;
        }
        public Class<? extends Client> getDefaultClientClass() {
            return defaultClientClass;
        }
    }
    ```
    Since that, users do have the chice to configure a default docoder for most of their interfaces with ```@FeignClien``` annotation via configuration type, rather than in properties file: 
    ```java
    @Configuration
    public class FeignConfig {
        @Bean
        public Decoder feignDecoder() {
            return new Decoder(){
                @Override
                public Object decode(Response response, Type type) throws IOException {
                    //TODO customization here
                    return result;
                }
            };
        }
    }
    ```
    Or just configure via @FeignClient (with the new feature you brought in) for specific interfaces: 
    ```java
    @FeignClient(url = "${postman-echo.domain}", decoderBean = "myDecoder")
    public interface PostmanEchoClient {
        @RequestLine("POST /post?foo1={foo1}&foo2={foo2}")
        PostPostRespDTO postPost(@Param("foo1") String foo1, @Param("foo2") String foo2);
    }
    ```

I am thinking about to merge this PR and do the tricks I mentioned above, to release the version 1.2.0, 
and you can start working on what you mentioned on the [comment-761522804](https://github.com/ethancommitpush/spring-boot-starter-openfeign/pull/3#issuecomment-761522804). How about that?
Cheers.

**Comment by qiangyt** [comment]
Great comments! I will update the PR soon.

For https://github.com/ethancommitpush/spring-boot-starter-openfeign/pull/3#issuecomment-761522804, yes, I think so.

**Comment by qiangyt** [comment]
@ethancommitpush , I'm working on other changes for this PR.

**Comment by qiangyt** [comment]
@ethancommitpush , I finished the updates.

**Comment by ethancommitpush** [comment]
@qiangyt got it, 
I will review it in 2 days, 
and if it went well I will release the new version.

**Comment by ethancommitpush** [comment]
@qiangyt So nice to have you bringing tremendous features in!
I will release version 1.2.0 tomorrow.

**Comment by ethancommitpush** [comment]
@qiangyt
The version 1.2.0 has been released based on this PR and some changes I made following your suggestions on the [comment-761522346](https://github.com/ethancommitpush/spring-boot-starter-openfeign/pull/3#issuecomment-761522346): 
> 1&#46; specify a class then will instantiate it, e.g. FeignClient.decoder
>
> The PR could be quite simplified if approach # 1 is removed.

**Pull request merged**
